### ISSUE TITLE
Edit readme

### ISSUE THREAD

**Issue by Superhuman07** [Superhuman07/Image-to-ASCII-Character-Script#1]

**Comment by yrahul3910** [comment]
What do you want in the README? Also, it seems you've put Python code in a .txt file. Should I change that in the PR as well?

**Comment by Superhuman07** [comment]
Umm. no 
I have already done that, if you are doing this for hacktoberfest you can use your own repo and create PR's it will be counted as such for the tee.

**Comment by yrahul3910** [comment]
Okay, thanks.
